### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by suhailshah** [BipinPaudel/JSP_Servlet_Quiz_app#1]
What about the database tables? Do you provide any of the sql code?

**Comment by BipinPaudel** [comment]
The project has not finished yet. It's going on still. I will have sql file uploaded.

**Comment by suhailshah** [comment]
Where usually people put the sql file since most of the git hub project that I open seems like no database sql provided. Like this project https://github.com/alinaMihai/quizApplication ...

**Comment by BipinPaudel** [comment]
You should be able to go through the code and find out the name and tables of the database.

**Comment by suhailshah** [comment]
Got it. Thanks.
